-- 私聊系统数据库初始化脚本（PostgreSQL）
--
-- 说明：
-- 1. 这里默认目标数据库已经由 docker-compose 的 POSTGRES_DB 创建完成。
-- 2. 如果你手动初始化，请先创建 private_chat 数据库，再执行本脚本。

-- 用户表
CREATE TABLE IF NOT EXISTS t_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) NOT NULL UNIQUE,
    password   VARCHAR(128) NOT NULL,
    nickname   VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 关系表
CREATE TABLE IF NOT EXISTS t_relation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    target_id  BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_relation UNIQUE (user_id, target_id)
);

CREATE INDEX IF NOT EXISTS idx_relation_user ON t_relation (user_id);

-- 消息表
CREATE TABLE IF NOT EXISTS t_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    sender_id       BIGINT NOT NULL,
    receiver_id     BIGINT NOT NULL,
    msg_type        SMALLINT NOT NULL,
    content         TEXT,
    file_url        VARCHAR(512),
    file_name       VARCHAR(255),
    file_size       BIGINT,
    is_read         SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_message_msg_type CHECK (msg_type IN (1, 2, 3, 4)),
    CONSTRAINT ck_message_is_read CHECK (is_read IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_message_conversation
    ON t_message (conversation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_message_receiver_unread
    ON t_message (receiver_id, is_read, created_at);

CREATE INDEX IF NOT EXISTS idx_message_conv_sender_receiver_read
    ON t_message (conversation_id, sender_id, receiver_id, is_read);

-- 测试用户（密码都是 123456 的 BCrypt 加密）
-- BCrypt("123456") = $2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi
INSERT INTO t_user (id, username, password, nickname) VALUES
    (1, 'alice', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '爱丽丝'),
    (2, 'bob', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '鲍勃'),
    (3, 'charlie', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '查理')
ON CONFLICT (id) DO NOTHING;

-- 测试关系（双向）
INSERT INTO t_relation (user_id, target_id) VALUES
    (1, 2),
    (2, 1),
    (1, 3),
    (3, 1),
    (2, 3),
    (3, 2)
ON CONFLICT (user_id, target_id) DO NOTHING;
